apiVersion: v1
kind: Service
metadata:
  name: ci-ui-webapp
  labels:
    app: ci-ui-webapp
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8090
      targetPort: 8090
  selector:
    appName: ci-ui-webapp