# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - IW-UI-Docker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://iwuiacr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_bd1aa823f7894bceb52d5e8a236b51c8 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_de0178d8b299471193f1a7cf904fb5a1 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: iwuiacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_bd1aa823f7894bceb52d5e8a236b51c8 }}/table-service:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'IW-UI-Docker'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_ae952b040c5d4cf38a2efbad2192e2e5 }}
        images: 'iwuiacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_bd1aa823f7894bceb52d5e8a236b51c8 }}/table-service:${{ github.sha }}'