# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - iwui

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://iwciacr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_cd0cee0b7f854e8e95b18e7083e7738d }}
        password: ${{ secrets.AzureAppService_ContainerPassword_f2f0f17d91ae4cd79f9b3c15a56570ee }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: iwciacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_cd0cee0b7f854e8e95b18e7083e7738d }}/table:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'iwui'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_beaee1cbad1443f18268e280a450a452 }}
        images: 'iwciacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_cd0cee0b7f854e8e95b18e7083e7738d }}/table:${{ github.sha }}'